Repository vignetteapp/vignette, pull requests merged in 2020-09, with the labels that each got.

#24 Initial Implementation of the Face Tracking Worker
  holotrack/Screens/Main/FaceTrackingWorker.cs
  holotrack/Vision/FaceTracking.cs
Labels: enhancement, priority:high

#35 Improve Face Tracking Test Scene
  holotrack.Tests/Visual/Tracking/TestSceneFaceTracking.cs
Labels: enhancement, priority:low

#39 Reducing Bitmap Size for Face Detection and Landmark Tracking
  holotrack/Tracking/FaceTracker.cs
Labels: enhancement, priority:high

#40 Make Face Tracker component abstract
  holotrack.Tests/Visual/Tracking/TestSceneFaceTracking.cs
  holotrack/HoloTrackGameBase.cs
  holotrack/Tracking/Face.cs
  holotrack/Tracking/FacePart.cs
  holotrack/Tracking/FaceRecognitionDotNetFaceTracker.cs
  holotrack/Tracking/FaceTracker.cs
Labels: documentation, enhancement, priority:low, wontfix

#47 Fix TestSceneFaceTracking, Tweak FaceTracker defaults
  holotrack.Tests/Visual/Tracking/TestSceneFaceTracking.cs
  holotrack/Tracking/FaceTracker.cs
Labels: enhancement, priority:high

#52 Add drag and drop file import support
  holotrack.Desktop/HoloTrackDesktop.cs
  holotrack.Tests/Visual/Interface/TestSceneDropdown.cs
  holotrack.Tests/Visual/Interface/TestSceneSettingsControls.cs
  holotrack/Graphics/Interface/HoloTrackDropdown.cs
  holotrack/Graphics/Interface/HoloTrackMenu.cs
  holotrack/HoloTrackGameBase.cs
  holotrack/IO/FileMetadata.cs
  holotrack/IO/FileStore.cs
  holotrack/IO/FileType.cs
  holotrack/IO/Imports/BackgroundImporter.cs
  holotrack/IO/Imports/CubismAssetImporter.cs
  holotrack/IO/Imports/Importer.cs
  holotrack/IO/UserCubismAssetStore.cs
  holotrack/Overlays/Settings/Sections/Appearance/BackgroundSelect.cs
  holotrack/Overlays/Settings/Sections/Appearance/BackgroundSettings.cs
  holotrack/Overlays/Settings/Sections/Appearance/ModelSelect.cs
  holotrack/Overlays/Settings/Sections/Appearance/ModelSettings.cs
  holotrack/Overlays/Settings/SettingsDropdown.cs
  holotrack/Overlays/Settings/SettingsOverlay.cs
  holotrack/Overlays/SidePanel/CameraDisplay.cs
  holotrack/Screens/Main/AdjustableBackground.cs
  holotrack/Screens/Main/AdjustableCubismSprite.cs
  holotrack/holotrack.csproj
Labels: enhancement
